//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDA.SRS.Processing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FDA.SRS.Processing.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;acidgroups&gt;
        ///  &lt;!-- OSO3H--&gt;
        ///  &lt;acidgroup rank=&quot;10&quot; acid=&quot;OS(=O)(=O)[O;H]&quot; base=&quot;OS(=O)(=O)[O-]&quot; acid2base=&quot;[*:1][O:2][S:3](=[O:4])(=[O:5])[O:6][H:7]&gt;&gt;[*:1][O:2][S:3](=[O:4])(=[O:5])[O-:6].[H+:7]&quot; base2acid=&quot;[*:1][O:2][S:3](=[O:4])(=[O:5])[O-:6].[H+:7]&gt;&gt;[*:1][O:2][S:3](=[O:4])(=[O:5])[O:6][H:7]&quot;/&gt;
        ///  
        ///  &lt;!-- SO3H--&gt;
        ///  &lt;acidgroup rank=&quot;20&quot; acid=&quot;[!O]S(=O)(=O)[O;H]&quot; base=&quot;[!O]S(=O)(=O)[O-]&quot; acid2base=&quot;[!O:1][S:2](=[O:3])(=[O:4])[O:5][H:6]&gt;&gt;[!O:1][S:2](=[O:3])(=[O:4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string acidgroups {
            get {
                return ResourceManager.GetString("acidgroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;subjectOf&gt;
        ///  &lt;characteristic&gt;
        ///    &lt;code code=&quot;C103201&quot; codeSystem=&quot;2.16.840.1.113883.3.26.1.1&quot; displayName=&quot;Optical Activity&quot; /&gt;
        ///    &lt;value xsi:type=&quot;CV&quot; code=&quot;{OPTCODE}&quot; codeSystem=&quot;2.16.840.1.113883.3.26.1.1&quot; displayName=&quot;{OPTACT}&quot; /&gt;
        ///  &lt;/characteristic&gt;
        ///&lt;/subjectOf&gt;
        ///.
        /// </summary>
        internal static string spl_optact_tmpl {
            get {
                return ResourceManager.GetString("spl_optact_tmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;?xml-stylesheet href=&quot;http://www.accessdata.fda.gov/spl/stylesheet/spl.xsl&quot; type=&quot;text/xsl&quot;?&gt;
        ///&lt;document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;urn:hl7-org:v3&quot; xsi:schemaLocation=&quot;urn:hl7-org:v3 http://www.accessdata.fda.gov/spl/schema/spl.xsd&quot;&gt;
        ///  &lt;id root=&quot;{ID}&quot; /&gt;
        ///  &lt;code code=&quot;64124-1&quot; codeSystem=&quot;2.16.840.1.113883.6.1&quot; displayName=&quot;Indexing - Substance&quot; /&gt;
        ///  &lt;title /&gt;
        ///  &lt;effectiveTime value=&quot;{EFFECTIVE_TIME}&quot; /&gt;
        ///  &lt;setId root=&quot;{SET_ID}&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spl_std_tmpl {
            get {
                return ResourceManager.GetString("spl_std_tmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;subjectOf&gt;
        ///  &lt;characteristic&gt;
        ///    &lt;code code=&quot;C18188&quot; codeSystem=&quot;2.16.840.1.113883.3.26.1.1&quot; displayName=&quot;Stereochemistry Type&quot; /&gt;
        ///    &lt;value xsi:type=&quot;CV&quot; code=&quot;{STEREOCODE}&quot; codeSystem=&quot;2.16.840.1.113883.3.26.1.1&quot; displayName=&quot;{STEREOTYPE}&quot; /&gt;
        ///  &lt;/characteristic&gt;
        ///&lt;/subjectOf&gt;
        ///.
        /// </summary>
        internal static string spl_stereotype_tmpl {
            get {
                return ResourceManager.GetString("spl_stereotype_tmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;subjectOf&gt;
        ///  &lt;characteristic&gt;
        ///    &lt;code code=&quot;9995-9&quot; codeSystem=&quot;2.16.840.1.113883.6.1&quot; displayName=&quot;SRS Unique Identifier&quot; /&gt;
        ///    &lt;value xsi:type=&quot;CV&quot; codeSystem=&quot;2.16.840.1.113883.3.26.1.1&quot;&gt;{UID}&lt;/value&gt;
        ///  &lt;/characteristic&gt;
        ///&lt;/subjectOf&gt;
        ///.
        /// </summary>
        internal static string spl_uid_tmpl {
            get {
                return ResourceManager.GetString("spl_uid_tmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;rules&gt;
        ///  &lt;!-- serious warnings that will prevent a Molecule being generated--&gt;
        ///  &lt;genericrules&gt;
        ///    &lt;!-- do not uncomment - this check issues incorrect error for atoms with aromatic bonds. Molecule needs to be dearomoatized before this check.
        ///    it is being handled
        ///    &lt;error id=&quot;G0&quot; title=&quot;incorrect valence&quot; message=&quot;an atom has a wrong valence&quot;&gt;
        ///      &lt;test name=&quot;HasIncorrectValence&quot; param=&quot;&quot;/&gt;
        ///    &lt;/error&gt;
        ///    --&gt;
        ///    &lt;error id=&quot;5000&quot; title=&quot;invalid ato [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidationRules {
            get {
                return ResourceManager.GetString("ValidationRules", resourceCulture);
            }
        }
    }
}
