//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDA.SRS.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FDA.SRS.Utils.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] polymer_Win32 {
            get {
                object obj = ResourceManager.GetObject("polymer_Win32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] seq2mol_Linux {
            get {
                object obj = ResourceManager.GetObject("seq2mol_Linux", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] seq2mol_Win32 {
            get {
                object obj = ResourceManager.GetObject("seq2mol_Win32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNII|Primary Name|Hash Code|Link|SetId|Version Number|Load Time|Citation
        ///MA3RM4FRWI||02fc78e0-3625-f20f-5537-2abc15115908|381b7725-2b64-4935-8ccf-079240820f68|ba7e55b9-98bd-4ee1-a1cd-03e6aec3b703|1|20140505123519|
        ///3Q3142VF7K||63af9506-a8a1-8650-a815-068d9661c480|a2cfd062-d4dc-4048-86d4-c6c6b19f203b|6105b959-def1-4308-9e22-1aa7cb70c786|1|20140510051433|
        ///S77P977AG8||aa6cf07a-c5ce-252d-3e64-2fa23f7a8b85|4e10e1a1-4d76-4f1e-980a-ebde95bdaf13|884b2b96-2795-45e1-a665-4bf962cee733|1|20140507153726|
        ///3O63K300I5|| [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubstanceIndexing {
            get {
                return ResourceManager.GetString("SubstanceIndexing", resourceCulture);
            }
        }
    }
}
