//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDA.SRS.ObjectModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FDA.SRS.ObjectModel.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///  6  5  0  0001  0  0  0  0  0999 V2000
        ///    1.1509    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    0.0000   -1.9943    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    2.3053   -3.3250    0.0000 N   0  0  0  0  0  0  0  0  0  0  0
        ///    1.1509   -1.3307    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    2.3053   -1.9943    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    3.4563   -1.3307    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  1  4  2  0
        ///  2  4  1  0
        ///  5  3  1  6
        ///  4  5  1  0
        ///  5  6  1  0
        ///M  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AA {
            get {
                return ResourceManager.GetString("AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ACCLDraw09121810362D
        ///
        /// 23 25  0  0  1  0  0  0  0  0999 V2000
        ///    0.6134   -9.6306    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    5.0645  -12.3226    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.8616  -12.3226    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    5.0111  -10.0808    0.0000 N   0  0  3  0  0  0  0  0  0  0  0  0
        ///    4.1938  -10.3471    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.7491  -10.7552    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///    4.5428  -11.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
    }
}
